---
- name: "{{ ansible_os_family }} install base packages"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ base_packages }}"
    - "{{ environment_base_packages }}"
    - "{{ host_base_packages }}"
  tags:
    - packages
