---
- name: "import environment specific variables"
  include_vars: "{{ ansible_distribution  | lower }}.yaml"
  tags:
    - variables

- name: "install base packages"
  include_tasks: "{{ ansible_os_family  | lower }}-base-packages.yaml"
  tags:
    - packages

- name: "install pip packages"
  include_tasks: "pip-packages.yml"
  tags:
    - pip
    - packages
